/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Matrix_Using_AWT;

/**
 *
 * @author Ramanand Anand Mohare.
 */
public class Determinant extends javax.swing.JFrame {
    
    FirstPage datatrans;
    public Determinant(FirstPage df) {
        initComponents();
        datatrans = df;
    }
    private Determinant()
    {
        throw new UnsupportedOperationException("Not Supported Yet.");
    }

    /**
     * Creates new form Determinant
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        E1 = new javax.swing.JTextField();
        E2 = new javax.swing.JTextField();
        E3 = new javax.swing.JTextField();
        E4 = new javax.swing.JTextField();
        E5 = new javax.swing.JTextField();
        E6 = new javax.swing.JTextField();
        E7 = new javax.swing.JTextField();
        E8 = new javax.swing.JTextField();
        E9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("Determinant");
        getContentPane().setLayout(null);

        jLabel1.setText("Enter Matrix  :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(56, 56, 101, 20);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(82, 692, 95, 29);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(324, 692, 69, 29);
        getContentPane().add(E1);
        E1.setBounds(239, 53, 70, 26);
        getContentPane().add(E2);
        E2.setBounds(318, 53, 70, 26);
        getContentPane().add(E3);
        E3.setBounds(406, 53, 70, 26);
        getContentPane().add(E4);
        E4.setBounds(239, 97, 70, 26);

        E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5ActionPerformed(evt);
            }
        });
        getContentPane().add(E5);
        E5.setBounds(318, 97, 70, 26);

        E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E6ActionPerformed(evt);
            }
        });
        getContentPane().add(E6);
        E6.setBounds(406, 97, 70, 26);

        E7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E7ActionPerformed(evt);
            }
        });
        getContentPane().add(E7);
        E7.setBounds(239, 139, 70, 26);

        E8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E8ActionPerformed(evt);
            }
        });
        getContentPane().add(E8);
        E8.setBounds(318, 139, 70, 26);

        E9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E9ActionPerformed(evt);
            }
        });
        getContentPane().add(E9);
        E9.setBounds(406, 139, 70, 26);

        jLabel2.setText("Determinant :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(56, 414, 101, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 410, 246, 26);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(519, 692, 65, 29);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(165, 95));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(705, 53, 328, 112);

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //Clear given matrix elements :
        E1.setText(" ");
        E2.setText(" ");
        E3.setText(" ");
        E4.setText(" ");
        E5.setText(" ");
        E6.setText(" ");
        E7.setText(" ");
        E8.setText(" ");
        E9.setText(" ");
        
        //Clear given answer :
        jTextField1.setText(" ");
        jTextArea1.setText(" ");
    }                                        

    private void E5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void E6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void E7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void E8ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void E9ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int[][] a = new int[3][3];
        
        //Calling matrix elements :
        String A = E1.getText();
        int a00 = Integer.parseInt(A);
        String B = E2.getText();
        int a01 = Integer.parseInt(B);
        String C = E3.getText();
        int a02 = Integer.parseInt(C);
        String D = E4.getText();
        int a10 = Integer.parseInt(D);
        String E = E5.getText();
        int a11 = Integer.parseInt(E);
        String F = E6.getText();
        int a12 = Integer.parseInt(F);
        String G = E7.getText();
        int a20 = Integer.parseInt(G);
        String H = E8.getText();
        int a21 = Integer.parseInt(H);
        String I = E9.getText();
        int a22 = Integer.parseInt(I);
        
        //Assigning matrix elements :
        a[0][0] = a00;
        a[0][1] = a01;
        a[0][2] = a02;
        a[1][0] = a10;
        a[1][1] = a11;
        a[1][2] = a12;
        a[2][0] = a20;
        a[2][1] = a21;
        a[2][2] = a22;
        
        //To find determinant of the matrix :
        int det = a[0][0]*(a[1][1]*a[2][2] - a[1][2]*a[2][1]) - a[0][1]*(a[1][0]*a[2][2] - a[1][2]*a[2][0]) + a[0][2]*(a[1][0]*a[2][1] - a[1][1]*a[2][0]);
        
        //Diplay of answer :
        String z = Integer.toString(det);
        jTextField1.setText(z);
        jTextArea1.setText("Procedure :\n|A| = " + " "+E1.getText()+ "*[ " +E5.getText()+ "* " +E9.getText()+ " - " +E6.getText()+ "*" +E8.getText()+ " ] - " +E2.getText()+ "*[ " +E4.getText()+ "* " +E9.getText()+ " - " +E6.getText()+ "*" +E7.getText()+ " ] + " +E3.getText()+ "*[ " +E4.getText()+ "* " +E8.getText()+ " - " +E5.getText()+ "*" +E7.getText()+ " ] " + "\n  =" +jTextField1.getText());
    }                                        

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {                                     
        datatrans.postData();
        this.setVisible(false);
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Determinant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Determinant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Determinant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Determinant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Determinant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Back;
    private javax.swing.JTextField E1;
    private javax.swing.JTextField E2;
    private javax.swing.JTextField E3;
    private javax.swing.JTextField E4;
    private javax.swing.JTextField E5;
    private javax.swing.JTextField E6;
    private javax.swing.JTextField E7;
    private javax.swing.JTextField E8;
    private javax.swing.JTextField E9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
