/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Matrix_Using_AWT;

/**
 *
 * @author Ramanand Anand Mohare.
 */
public class EigenValues extends javax.swing.JFrame {

    FirstPage datatrans;
    public EigenValues(FirstPage df) {
        initComponents();
        datatrans = df;
    }
    private EigenValues()
    {
        throw new UnsupportedOperationException("Not Supported Yet.");
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        E1 = new javax.swing.JTextField();
        E2 = new javax.swing.JTextField();
        E3 = new javax.swing.JTextField();
        E4 = new javax.swing.JTextField();
        E5 = new javax.swing.JTextField();
        E6 = new javax.swing.JTextField();
        E7 = new javax.swing.JTextField();
        E8 = new javax.swing.JTextField();
        E9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setTitle("Eigen Values");
        getContentPane().setLayout(null);

        jLabel1.setText("Enter Matrix  :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(56, 56, 101, 20);
        getContentPane().add(E1);
        E1.setBounds(239, 53, 70, 26);
        getContentPane().add(E2);
        E2.setBounds(318, 53, 70, 26);
        getContentPane().add(E3);
        E3.setBounds(406, 53, 70, 26);
        getContentPane().add(E4);
        E4.setBounds(239, 97, 70, 26);

        E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5ActionPerformed(evt);
            }
        });
        getContentPane().add(E5);
        E5.setBounds(318, 97, 70, 26);

        E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E6ActionPerformed(evt);
            }
        });
        getContentPane().add(E6);
        E6.setBounds(406, 97, 70, 26);

        E7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E7ActionPerformed(evt);
            }
        });
        getContentPane().add(E7);
        E7.setBounds(239, 139, 70, 26);

        E8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E8ActionPerformed(evt);
            }
        });
        getContentPane().add(E8);
        E8.setBounds(318, 139, 70, 26);

        E9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E9ActionPerformed(evt);
            }
        });
        getContentPane().add(E9);
        E9.setBounds(406, 139, 70, 26);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 510, 95, 29);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 510, 69, 29);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(580, 510, 65, 29);

        jLabel2.setText("Eigen Values  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 290, 106, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(239, 288, 250, 26);

        pack();
    }// </editor-fold>                        

    private void E5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void E6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void E7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void E8ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void E9ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int[][] a = new int[3][3];
        int w=0;
        double e,f,g,h,i,j,k,l,m,n,p,r,s,t,u,x1 = 0,x2 = 0,x3 = 0;
             
        //Calling Matrix elements :
        String A = E1.getText();
        int a00 = Integer.parseInt(A);
        String B = E2.getText();
        int a01 = Integer.parseInt(B);
        String C = E3.getText();
        int a02 = Integer.parseInt(C);
        String D = E4.getText();
        int a10 = Integer.parseInt(D);
        String E = E5.getText();
        int a11 = Integer.parseInt(E);
        String F = E6.getText();
        int a12 = Integer.parseInt(F);
        String G = E7.getText();
        int a20 = Integer.parseInt(G);
        String H = E8.getText();
        int a21 = Integer.parseInt(H);
        String I = E9.getText();
        int a22 = Integer.parseInt(I);
        
        //Assigning Matrix elements :
        a[0][0] = a00;
        a[0][1] = a01;
        a[0][2] = a02;
        a[1][0] = a10;
        a[1][1] = a11;
        a[1][2] = a12;
        a[2][0] = a20;
        a[2][1] = a21;
        a[2][2] = a22;
        
        //Eigen Values Calculations :
        //To find determinant :
        double det = (a[0][0]*(a[1][1]*a[2][2] - a[1][2]*a[2][1]) - a[0][1]*(a[1][0]*a[2][2] - a[1][2]*a[2][0]) + a[0][2]*(a[1][0]*a[2][1] - a[1][1]*a[2][0]));
        det = det*(-1);

        //To find S1 :
        double S1 = a00+a11+a22;
        S1 = S1*(-1);

        //To find S2 :
        double S2 = (a[1][1]*a[2][2] - a[1][2]*a[2][1]) + (a[0][0]*a[2][2] - a[0][2]*a[2][0]) + (a[0][0]*a[1][1] - a[0][1]*a[1][0]);
        
        //Finding roots :     
        e=2.7182818284590;
        f=((3*S2/1)-(S1*S1/(1*1)))/3; // ** bracketed (a*a)!
        g=((2*S1*S1*S1/(1*1*1))-(9*S1*S2/(1*1))+(27*det/1))/27; // ** brackets!
        h=(g*g/4)+(f*f*f/27);
        i=Math.sqrt(((g*g/4)-h));  
        j=Math.exp(Math.log10(i)/Math.log10(e)/3);
        k=Math.acos((-1)*(g/(2*i)));
        l=j*(-1);
        m=Math.cos(k/3);
        n=Math.sqrt(3)*Math.sin(k/3);
        p=(S1/3*1)*(-1);
        r=(-1)*(g/2)+Math.sqrt(h);
        s=Math.exp(Math.log10(r)/Math.log10(e)/3);
        t=(-1)*(g/2)-Math.sqrt(h);
        u=Math.exp(Math.log10(t)/Math.log10(e)/3);
 
        if (h>0)w=1;
        if (h<=0)w=3;
        if ((f==0) && (g==0) && (h==0))w=2;

        switch ( w )
        {
            case 1:
               x1=(s+u)-(S1/3*1);
               x2=(-1)*(s+u)/2-(S1/3*1);
               x3=(s-u)*Math.sqrt(3)/2;
               //Display answer :
               //String P = Integer.toString((int) x1);
               //String Q = Integer.toString((int) x2);
               //String R = Integer.toString((int) x3);
               int a1 = (int) x1;
               int a2 = (int) x2;
               int a3 = (int) x3;
               jTextField1.setText(a1+","+a2+","+a3);
               break;
            
            case 2:
                x1=Math.exp(Math.log10(det/1)/Math.log10(e)/3)*(-1);
                x2=0;
                x3=0;
                //Display answer :
                //String L = Integer.toString((int) x1);
                int a4 = (int) x1;
                jTextField1.setText(a4+","+x2+","+x3);
                break;

            case 3:
                x1=2*j*Math.cos(k/3)-(S1/3*1);
                x2=l*(m+n)+p;
                x3=l*(m-n)+p;
                //Display answer :
                //String X = Integer.toString((int) x1);
                //String Y = Integer.toString((int) x2);
                //String Z = Integer.toString((int) x3);
                int a5 = (int) x1;
                int a6 = (int) x2;
                int a7 = (int) x3;
                jTextField1.setText(a5+","+a6+","+a7);
                break;
        }
    }                                        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //Clear given Matrix elements :
        E1.setText(" ");
        E2.setText(" ");
        E3.setText(" ");
        E4.setText(" ");
        E5.setText(" ");
        E6.setText(" ");
        E7.setText(" ");
        E8.setText(" ");
        E9.setText(" ");
        
        //Clear given answer :
        jTextField1.setText(" ");
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        datatrans.postData();
        this.setVisible(false);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EigenValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EigenValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EigenValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EigenValues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EigenValues().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField E1;
    private javax.swing.JTextField E2;
    private javax.swing.JTextField E3;
    private javax.swing.JTextField E4;
    private javax.swing.JTextField E5;
    private javax.swing.JTextField E6;
    private javax.swing.JTextField E7;
    private javax.swing.JTextField E8;
    private javax.swing.JTextField E9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
