/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Matrix_Using_AWT;

/**
 *
 * @author Ramanand Anand Mohare.
 */
public class Display extends javax.swing.JFrame {

    FirstPage datatrans;
    public Display(FirstPage df) {
        initComponents();
        datatrans = df;
    }
    private Display()
    {
        throw new UnsupportedOperationException("Not Supported Yet.");
    }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        E1 = new javax.swing.JTextField();
        E3 = new javax.swing.JTextField();
        E4 = new javax.swing.JTextField();
        E6 = new javax.swing.JTextField();
        E7 = new javax.swing.JTextField();
        E9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        E2 = new javax.swing.JTextField();
        E8 = new javax.swing.JTextField();
        E5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setTitle("Matrix Type");
        getContentPane().setLayout(null);

        jLabel1.setText("Enter the Matrix       :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 96, 153, 26);
        getContentPane().add(E1);
        E1.setBounds(335, 96, 70, 26);
        getContentPane().add(E3);
        E3.setBounds(525, 96, 70, 26);
        getContentPane().add(E4);
        E4.setBounds(335, 142, 70, 26);
        getContentPane().add(E6);
        E6.setBounds(525, 142, 70, 26);
        getContentPane().add(E7);
        E7.setBounds(335, 188, 70, 26);
        getContentPane().add(E9);
        E9.setBounds(525, 188, 70, 26);

        jLabel2.setText("Type Of Matrix        :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 368, 153, 35);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(335, 372, 297, 26);

        jButton1.setText("Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(146, 602, 75, 29);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(393, 602, 69, 29);
        getContentPane().add(E2);
        E2.setBounds(423, 96, 70, 26);
        getContentPane().add(E8);
        E8.setBounds(423, 188, 70, 26);
        getContentPane().add(E5);
        E5.setBounds(423, 142, 70, 26);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(618, 602, 65, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Clear given matrix elements :
        E1.setText(" ");
        E2.setText(" ");
        E3.setText(" ");
        E4.setText(" ");
        E5.setText(" ");
        E6.setText(" ");
        E7.setText(" ");
        E8.setText(" ");
        E9.setText(" ");
        
        //Clear given answer-box :
        jTextField1.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int[][] a = new int[3][3];
        
        //Calling matrix elements from user :
        String A = E1.getText();
        int a00 = Integer.parseInt(A);
        String B = E1.getText();
        int a01 = Integer.parseInt(B);
        String C = E1.getText();
        int a02 = Integer.parseInt(C);
        String D = E1.getText();
        int a10 = Integer.parseInt(D);
        String E = E1.getText();
        int a11 = Integer.parseInt(E);
        String F = E1.getText();
        int a12 = Integer.parseInt(F);
        String G = E1.getText();
        int a20 = Integer.parseInt(G);
        String H = E1.getText();
        int a21 = Integer.parseInt(H);
        String I = E1.getText();
        int a22 = Integer.parseInt(I);
       
        //Assigning matrix elements :
        a[0][0] = a00;
        a[0][1] = a01;
        a[0][2] = a02;
        a[1][0] = a10;
        a[1][1] = a11;
        a[1][2] = a12;
        a[2][0] = a20;
        a[2][1] = a21;
        a[2][2] = a22;
        
        //Checking for Null Matrix :
        if(a00==0 && a01==0 && a02==0 && a10==0 && a12==0 && a11==0 && a20==0 && a21==0 && a22==0)
        {
            jTextField1.setText("Null Matrix");
        }
        
        //Checking for Unit Matrix :
        else if(a00==1 && a01==1 && a02==1 && a10==1 && a11==1 && a12==1 && a20==1 && a21==1 && a22==1)
        {
            jTextField1.setText("Unit Matrix");
        }
        
        //Checking for Upper Traingular Matrix :
        else if((a10 + a20 + a21 == 0) && (a00>0 && a01>0 && a02>0 && a11>0 && a12>0 && a22>0))
        {
            jTextField1.setText("Upper Traingular Matrix");
        }
        
        //Checking for Lower Triangular Matrix :
        else if((a01 + a02 + a12 == 0) && (a00>0 && a11>0 && a22>0 && a10>0 && a20>0 && a22>0))
        {
            jTextField1.setText("Lower Traingular Matrix");
        }
        
        //Checking for Diagonal & Scalar Matrix :
        else if(a00>0 && a01==0 && a02==0 && a10==0 && a11>0 && a12==0 && a20==0 && a21==0 && a22>0)
        {
            int k=a00;
            if(a00/k==1 && a11/k==1 && a22/k==1)
            {
                jTextField1.setText("Scalar Matrix");                
            }
            else
            {
                jTextField1.setText("Diagonal Matrix");
            }
        }
        
        else
        {
            jTextField1.setText("General Matrix");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        datatrans.postData();
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField E1;
    private javax.swing.JTextField E2;
    private javax.swing.JTextField E3;
    private javax.swing.JTextField E4;
    private javax.swing.JTextField E5;
    private javax.swing.JTextField E6;
    private javax.swing.JTextField E7;
    private javax.swing.JTextField E8;
    private javax.swing.JTextField E9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
